import type { Metadata } from "next";

import { ThemeProvider } from "next-themes";
import {Lang} from "@/context/LanguageContext";
import {Fon} from "@/context/FontSize";
import { WrapLines } from "@/context/wrapLines";
import { Them } from "@/context/ThemContext";
import "./globals.css";
import {Bg} from "@/context/bgContext"
import { Bgenabled } from "@/context/bgEnabled";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Lang>
<Them>
    <Fon>
        <WrapLines>
            <Bg>
                <Bgenabled>

        {children}
                </Bgenabled>

            </Bg>
        </WrapLines>



    </Fon>
</Them>
            </Lang>
          </ThemeProvider>
        </body>
    </html>
  );
}
